# Generated by Django 5.2.12 on 2026-04-02 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='meeting_location',
        ),
        migrations.RemoveField(
            model_name='order',
            name='meeting_time',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilyapti'), ('agreed', 'Tasdiqlangan'), ('completed', 'Sotib olingan'), ('canceled', 'Bekor qilingan')], default='pending', max_length=20),
        ),
    ]
