# Generated by Django 5.2.12 on 2026-03-27 19:43

import django.db.models.deletion
import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('condition', models.CharField(choices=[('new', 'Yangi'), ('ideal', 'Ideal'), ('good', 'Yaxshi'), ('normal', 'Qoniqarli')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_type', models.CharField(choices=[('fixed', "Qat'iy"), ('negotiable', 'Kelishiladi'), ('free', 'Bepul'), ('exchange', 'Ayirboshlash')], max_length=20)),
                ('region', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('favorite_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('moderation', 'Moderatsiyada'), ('active', 'Aktiv'), ('rejected', 'Rad etilgan'), ('sold', 'Sotilgan'), ('archived', 'Arxivlangan')], default='moderation', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(default=product.models.Product.default_expire)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('order', models.PositiveIntegerField()),
                ('is_main', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.ImageField(blank=True, upload_to='categories/')),
                ('description', models.TextField(blank=True, max_length=512)),
                ('is_active', models.BooleanField(default=True)),
                ('order_num', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='product.category')),
            ],
        ),
    ]
