# Generated by Django 5.2.12 on 2026-03-27 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('logo', models.ImageField(blank=True, upload_to='brands/')),
            ],
            options={
                'verbose_name': 'Brend',
                'verbose_name_plural': 'Brendlar',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('hex_code', models.CharField(blank=True, max_length=7)),
            ],
            options={
                'verbose_name': 'Rang',
                'verbose_name_plural': 'Ranglar',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Sevimli', 'verbose_name_plural': 'Sevimlilar'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Mahsulot', 'verbose_name_plural': 'Mahsulotlar'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-is_main', 'order'], 'verbose_name': 'Mahsulot rasmi', 'verbose_name_plural': 'Mahsulot rasmlari'},
        ),
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('clothing', 'Kiyim-kechak'), ('food', 'Oziq-ovqat'), ('household', "Xo'jalik mollari"), ('electronics', 'Elektronika'), ('other', 'Boshqa')], default='other', help_text="Toifa turi — mahsulotga qanday qo'shimcha maydonlar kerakligini aniqlaydi", max_length=20),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='product.product'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.brand'),
        ),
        migrations.CreateModel(
            name='ClothingAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], max_length=10)),
                ('size_number', models.PositiveIntegerField(blank=True, help_text='Raqamli razmer (masalan oyoq kiyim: 38, 39, 42 ...)', null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Erkak'), ('female', 'Ayol'), ('unisex', 'Uniseks'), ('kids', 'Bolalar')], max_length=10)),
                ('material', models.CharField(blank=True, help_text='Mato turi: paxta, teri, sintetik ...', max_length=100)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clothing_attr', to='product.product')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.color')),
            ],
            options={
                'verbose_name': 'Kiyim atributi',
                'verbose_name_plural': 'Kiyim atributlari',
            },
        ),
        migrations.CreateModel(
            name='ElectronicsAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(blank=True, help_text='Model nomi', max_length=200)),
                ('storage_gb', models.PositiveIntegerField(blank=True, help_text='Xotira hajmi (GB)', null=True)),
                ('ram_gb', models.PositiveIntegerField(blank=True, help_text='RAM hajmi (GB)', null=True)),
                ('screen_size', models.DecimalField(blank=True, decimal_places=1, help_text="Ekran o'lchami (dyuym)", max_digits=4, null=True)),
                ('battery_mah', models.PositiveIntegerField(blank=True, help_text="Batareya sig'imi (mAh)", null=True)),
                ('warranty_months', models.PositiveIntegerField(blank=True, help_text='Kafolat muddati (oy)', null=True)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.color')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='electronics_attr', to='product.product')),
            ],
            options={
                'verbose_name': 'Elektronika atributi',
                'verbose_name_plural': 'Elektronika atributlari',
            },
        ),
        migrations.CreateModel(
            name='FoodAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_date', models.DateField(blank=True, help_text='Yaroqlilik muddati', null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text="Og'irligi (gramm yoki kg)", max_digits=10, null=True)),
                ('weight_unit', models.CharField(choices=[('g', 'gramm'), ('kg', 'kilogramm'), ('l', 'litr'), ('ml', 'millilitr')], default='kg', max_length=5)),
                ('is_organic', models.BooleanField(default=False, help_text='Organik mahsulotmi?')),
                ('ingredients', models.TextField(blank=True, help_text='Tarkibi')),
                ('storage_info', models.CharField(blank=True, help_text='Saqlash sharoiti', max_length=200)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='food_attr', to='product.product')),
            ],
            options={
                'verbose_name': 'Oziq-ovqat atributi',
                'verbose_name_plural': 'Oziq-ovqat atributlari',
            },
        ),
        migrations.CreateModel(
            name='HouseholdAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(blank=True, help_text="Material: plastik, yog'och, metall ...", max_length=100)),
                ('dimensions', models.CharField(blank=True, help_text="O'lchamlari: 30x40x50 sm", max_length=100)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text="Og'irligi (kg)", max_digits=10, null=True)),
                ('warranty_months', models.PositiveIntegerField(blank=True, help_text='Kafolat muddati (oy)', null=True)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.color')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='household_attr', to='product.product')),
            ],
            options={
                'verbose_name': "Xo'jalik mol atributi",
                'verbose_name_plural': "Xo'jalik mol atributlari",
            },
        ),
    ]
