# Generated by Django 5.2.12 on 2026-03-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_brand_color_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Soliq foizi (masalan 10.00 = 10%)', max_digits=5),
        ),
    ]
