# Generated by Django 5.2.12 on 2026-03-28 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_tax_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='householdattribute',
            name='color',
        ),
        migrations.RemoveField(
            model_name='householdattribute',
            name='product',
        ),
        migrations.RemoveField(
            model_name='clothingattribute',
            name='size_number',
        ),
        migrations.AddField(
            model_name='clothingattribute',
            name='season',
            field=models.CharField(blank=True, choices=[('winter', 'Qishki'), ('summer', 'Yozgi'), ('spring', 'Bahorgi'), ('autumn', 'Kuzgi'), ('all', 'Barcha mavsumlar')], max_length=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('phone', '📱 Telefon'), ('tv', '📺 Televizor'), ('laptop', '💻 Noutbuk'), ('clothing', '👕 Kiyim'), ('shoes', '👟 Oyoq kiyim'), ('appliance', '🏠 Maishiy texnika'), ('auto', '🚗 Avtomobil'), ('food', '🍎 Oziq-ovqat'), ('furniture', '🪑 Mebel'), ('book', '📚 Kitob'), ('hobby', "🎮 O'yin va Hobbi"), ('other', '🔧 Boshqa')], default='other', help_text='Toifa turi — mahsulotga qanday atribut maydonlari kerakligini aniqlaydi', max_length=20),
        ),
        migrations.AlterField(
            model_name='clothingattribute',
            name='material',
            field=models.CharField(blank=True, help_text='paxta, teri, sintetik ...', max_length=100),
        ),
        migrations.AlterField(
            model_name='foodattribute',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='ApplianceAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(blank=True, max_length=200)),
                ('power_watt', models.PositiveIntegerField(blank=True, help_text='Quvvat (Vt)', null=True)),
                ('energy_class', models.CharField(blank=True, choices=[('a+++', 'A+++'), ('a++', 'A++'), ('a+', 'A+'), ('a', 'A'), ('b', 'B'), ('c', 'C')], max_length=5)),
                ('warranty_months', models.PositiveIntegerField(blank=True, help_text='Kafolat (oy)', null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text="Og'irligi (kg)", max_digits=8, null=True)),
                ('dimensions', models.CharField(blank=True, help_text="O'lcham: 60x60x85 sm", max_length=100)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.color')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appliance_attr', to='product.product')),
            ],
            options={
                'verbose_name': 'Maishiy texnika atributi',
                'verbose_name_plural': 'Maishiy texnika atributlari',
            },
        ),
        migrations.CreateModel(
            name='AutoAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(blank=True, help_text='Marka: Chevrolet, Toyota...', max_length=100)),
                ('model_name', models.CharField(blank=True, help_text='Model: Malibu, Camry...', max_length=100)),
                ('year', models.PositiveIntegerField(blank=True, help_text='Ishlab chiqarilgan yil', null=True)),
                ('fuel_type', models.CharField(blank=True, choices=[('petrol', 'Benzin'), ('diesel', 'Dizel'), ('gas', 'Gaz'), ('electric', 'Elektr'), ('hybrid', 'Gibrid')], max_length=10)),
                ('transmission', models.CharField(blank=True, choices=[('manual', 'Mexanika'), ('automatic', 'Avtomat'), ('robot', 'Robot'), ('cvt', 'Variator')], max_length=10)),
                ('drive_type', models.CharField(blank=True, choices=[('front', 'Oldi'), ('rear', 'Orqa'), ('awd', "To'liq")], max_length=5)),
                ('mileage_km', models.PositiveIntegerField(blank=True, help_text='Probeg (km)', null=True)),
                ('engine_cc', models.PositiveIntegerField(blank=True, help_text='Motor hajmi (cc)', null=True)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.color')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auto_attr', to='product.product')),
            ],
            options={
                'verbose_name': 'Avtomobil atributi',
                'verbose_name_plural': 'Avtomobil atributlari',
            },
        ),
        migrations.CreateModel(
            name='BookAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, help_text='Muallif', max_length=200)),
                ('publisher', models.CharField(blank=True, help_text='Nashriyot', max_length=200)),
                ('language', models.CharField(blank=True, help_text="Til: O'zbek, Rus, Ingliz...", max_length=50)),
                ('pages', models.PositiveIntegerField(blank=True, help_text='Sahifalar soni', null=True)),
                ('isbn', models.CharField(blank=True, help_text='ISBN raqami', max_length=20)),
                ('genre', models.CharField(blank=True, help_text='Janr: fantastika, tarix...', max_length=100)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book_attr', to='product.product')),
            ],
            options={
                'verbose_name': 'Kitob atributi',
                'verbose_name_plural': 'Kitob atributlari',
            },
        ),
        migrations.CreateModel(
            name='FurnitureAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(blank=True, help_text="yog'och, metall, plastik...", max_length=100)),
                ('dimensions', models.CharField(blank=True, help_text="O'lcham: 120x60x75 sm", max_length=100)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('warranty_months', models.PositiveIntegerField(blank=True, help_text='Kafolat (oy)', null=True)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.color')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='furniture_attr', to='product.product')),
            ],
            options={
                'verbose_name': 'Mebel atributi',
                'verbose_name_plural': 'Mebel atributlari',
            },
        ),
        migrations.CreateModel(
            name='HobbyAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby_type', models.CharField(blank=True, help_text="Turi: o'yinchoq, sport, musiqa...", max_length=100)),
                ('age_min', models.PositiveIntegerField(blank=True, help_text='Minimal yosh', null=True)),
                ('age_max', models.PositiveIntegerField(blank=True, help_text='Maksimal yosh', null=True)),
                ('material', models.CharField(blank=True, max_length=100)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hobby_attr', to='product.product')),
            ],
            options={
                'verbose_name': 'Hobbi atributi',
                'verbose_name_plural': 'Hobbi atributlari',
            },
        ),
        migrations.CreateModel(
            name='LaptopAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(blank=True, max_length=200)),
                ('processor', models.CharField(blank=True, help_text='Protsessor: Intel i7, Apple M2...', max_length=100)),
                ('ram_gb', models.PositiveIntegerField(blank=True, help_text='RAM (GB)', null=True)),
                ('storage_gb', models.PositiveIntegerField(blank=True, help_text='Xotira (GB)', null=True)),
                ('storage_type', models.CharField(blank=True, choices=[('ssd', 'SSD'), ('hdd', 'HDD'), ('emmc', 'eMMC')], max_length=10)),
                ('screen_size', models.DecimalField(blank=True, decimal_places=1, help_text='Ekran (dyuym)', max_digits=4, null=True)),
                ('battery_hours', models.PositiveIntegerField(blank=True, help_text='Batareya (soat)', null=True)),
                ('os', models.CharField(blank=True, choices=[('windows', 'Windows'), ('macos', 'macOS'), ('linux', 'Linux'), ('other', 'Boshqa')], max_length=10)),
                ('warranty_months', models.PositiveIntegerField(blank=True, null=True)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.color')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='laptop_attr', to='product.product')),
            ],
            options={
                'verbose_name': 'Noutbuk atributi',
                'verbose_name_plural': 'Noutbuk atributlari',
            },
        ),
        migrations.CreateModel(
            name='OtherAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(blank=True, max_length=100)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('warranty_months', models.PositiveIntegerField(blank=True, help_text='Kafolat (oy)', null=True)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.color')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='other_attr', to='product.product')),
            ],
            options={
                'verbose_name': 'Boshqa atribut',
                'verbose_name_plural': 'Boshqa atributlar',
            },
        ),
        migrations.CreateModel(
            name='PhoneAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(blank=True, help_text='Model: iPhone 15 Pro, Samsung S24...', max_length=200)),
                ('storage_gb', models.PositiveIntegerField(blank=True, help_text='Ichki xotira (GB)', null=True)),
                ('ram_gb', models.PositiveIntegerField(blank=True, help_text='RAM (GB)', null=True)),
                ('battery_mah', models.PositiveIntegerField(blank=True, help_text='Batareya (mAh)', null=True)),
                ('screen_size', models.DecimalField(blank=True, decimal_places=1, help_text='Ekran (dyuym)', max_digits=4, null=True)),
                ('os', models.CharField(blank=True, choices=[('android', 'Android'), ('ios', 'iOS'), ('other', 'Boshqa')], max_length=10)),
                ('sim_count', models.PositiveSmallIntegerField(blank=True, help_text='SIM karta soni', null=True)),
                ('camera_mp', models.PositiveIntegerField(blank=True, help_text='Kamera (MP)', null=True)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.color')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phone_attr', to='product.product')),
            ],
            options={
                'verbose_name': 'Telefon atributi',
                'verbose_name_plural': 'Telefon atributlari',
            },
        ),
        migrations.CreateModel(
            name='ShoesAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_number', models.PositiveIntegerField(blank=True, help_text='Razmer: 36, 38, 42...', null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Erkak'), ('female', 'Ayol'), ('unisex', 'Uniseks'), ('kids', 'Bolalar')], max_length=10)),
                ('material', models.CharField(blank=True, help_text='teri, zamsha, tekstil...', max_length=100)),
                ('season', models.CharField(blank=True, choices=[('winter', 'Qishki'), ('summer', 'Yozgi'), ('spring', 'Bahorgi'), ('autumn', 'Kuzgi'), ('all', 'Barcha mavsumlar')], max_length=10)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.color')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shoes_attr', to='product.product')),
            ],
            options={
                'verbose_name': 'Oyoq kiyim atributi',
                'verbose_name_plural': 'Oyoq kiyim atributlari',
            },
        ),
        migrations.CreateModel(
            name='TVAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(blank=True, max_length=200)),
                ('screen_size', models.PositiveIntegerField(blank=True, help_text='Ekran (dyuym)', null=True)),
                ('resolution', models.CharField(blank=True, choices=[('hd', 'HD (720p)'), ('fhd', 'Full HD (1080p)'), ('qhd', '2K (1440p)'), ('uhd', '4K (2160p)'), ('8k', '8K')], max_length=5)),
                ('is_smart', models.BooleanField(default=False, help_text='Smart TV')),
                ('refresh_rate', models.PositiveIntegerField(blank=True, help_text='Yangilanish tezligi (Hz)', null=True)),
                ('warranty_months', models.PositiveIntegerField(blank=True, help_text='Kafolat (oy)', null=True)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.color')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tv_attr', to='product.product')),
            ],
            options={
                'verbose_name': 'TV atributi',
                'verbose_name_plural': 'TV atributlari',
            },
        ),
        migrations.DeleteModel(
            name='ElectronicsAttribute',
        ),
        migrations.DeleteModel(
            name='HouseholdAttribute',
        ),
    ]
