# Generated by Django 5.2.12 on 2026-03-28 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_householdattribute_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='product',
            name='district',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='region',
        ),
    ]
