# Generated by Django 5.2.12 on 2026-03-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_product_condition_remove_product_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothingattribute',
            name='size',
        ),
        migrations.RemoveField(
            model_name='shoesattribute',
            name='size_number',
        ),
        migrations.AddField(
            model_name='clothingattribute',
            name='available_sizes',
            field=models.JSONField(blank=True, default=list, help_text='Mavjud razmerlar ro\'yxati, masalan: ["S", "M", "L", "XL"]'),
        ),
        migrations.AddField(
            model_name='shoesattribute',
            name='available_sizes',
            field=models.JSONField(blank=True, default=list, help_text="Mavjud razmerlar ro'yxati, masalan: [36, 37, 38, 39, 40]"),
        ),
    ]
