# Generated by Django 5.2.12 on 2026-03-29 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_clothingattribute_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingProductEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changes_json', models.JSONField(help_text="O'zgartirilgan maydonlar: {field: {old: ..., new: ...}}")),
                ('previous_status', models.CharField(help_text='Tahrirlashdan oldingi holat (tasdiqlanganda qaytariladi)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pending_edit', to='product.product')),
            ],
            options={
                'verbose_name': 'Kutilayotgan tahrir',
                'verbose_name_plural': 'Kutilayotgan tahrirlar',
            },
        ),
    ]
